server.port=9001
spring.application.name=flight-booking
#spring.ai.dashscope.api-key=${AI_DASHSCOPE_API_KEY}
#spring.ai.dashscope.api-key=sk-a8750c3d4f1b415bb8b6e096fbb6d3b0
#spring.ai.dashscope.chat.options.model=qwen-max
#spring.ai.ollama.base-url=http://127.0.0.1:11434
#spring.ai.ollama.chat.options.model=deepseek-r1:7b
#spring.ai.ollama.embedding.options.model=mxbai-embed-large:335m
spring.ai.openai.api-key=dc8c7567-a464-49e1-996b-e3e455ebdeb6
spring.ai.openai.base-url=https://ark.cn-beijing.volces.com/api/
spring.ai.openai.chat.options.model=deepseek-v3-250324
spring.ai.openai.embedding.options.model=doubao-embedding-text-240715
spring.ai.openai.chat.completions-path=/v3/chat/completions
spring.ai.openai.embedding.embeddings-path= /v3/embeddings
#spring.ai.qianfan.api-key=Ez2YGtKZLONGBS8zSYf4fI14
#spring.ai.qianfan.secret-key=VjNr9BWL6YMQtC1q3WADXwUlkOI3zQBK
#spring.ai.qianfan.base-url=https://aip.baidubce.com/rpc/2.0/ai_custom/v1/
#spring.ai.qianfan.chat.options.model=ernie-lite-pro-128k
#spring.ai.qianfan.embedding.options.model=tao_8k
spring.ai.mcp.client.name=mcp-client
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.type=ASYNC
spring.ai.mcp.client.sse.connections.server1.url=http://127.0.0.1:8088
