server.port=9001
spring.application.name=flight-booking
#spring.ai.dashscope.api-key=${AI_DASHSCOPE_API_KEY}
#spring.ai.dashscope.api-key=sk-a8750c3d4f1b415bb8b6e096fbb6d3b0
#spring.ai.dashscope.chat.options.model=qwen-max
spring.ai.ollama.base-url=http://127.0.0.1:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.embedding.options.model=mxbai-embed-large:335m