server.port=9001
spring.application.name=flight-booking
langchain4j.open-ai.chat-model.api-key= dc8c7567-a464-49e1-996b-e3e455ebdeb6
langchain4j.open-ai.chat-model.base-url= https://ark.cn-beijing.volces.com/api/v3/
langchain4j.open-ai.chat-model.model-name= deepseek-v3-250324

langchain4j.open-ai.streaming-chat-model.api-key= dc8c7567-a464-49e1-996b-e3e455ebdeb6
langchain4j.open-ai.streaming-chat-model.base-url= https://ark.cn-beijing.volces.com/api/v3/
langchain4j.open-ai.streaming-chat-model.model-name= deepseek-v3-250324

langchain4j.open-ai.chat-model.log-requests = true
langchain4j.open-ai.chat-model.log-responses = true
#spring.ai.openai.api-key=dc8c7567-a464-49e1-996b-e3e455ebdeb6
#spring.ai.openai.base-url=https://ark.cn-beijing.volces.com/api/
#spring.ai.openai.chat.options.model=deepseek-v3-250324
#spring.ai.openai.chat.completions-path=/v3/chat/completions

langchain4j.open-ai.embedding-model.api-key=dc8c7567-a464-49e1-996b-e3e455ebdeb6
langchain4j.open-ai.embedding-model.base-url=https://ark.cn-beijing.volces.com/api/v3/
langchain4j.open-ai.embedding-model.model-name= doubao-embedding-text-240715
#spring.ai.openai.embedding.options.model=doubao-embedding-text-240715
#spring.ai.openai.embedding.embeddings-path= /v3/embeddings

spring.ai.mcp.client.name=mcp-client
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.type=ASYNC
spring.ai.mcp.client.sse.connections.server1.url=http://127.0.0.1:8088




langchain4j.community.neo4j.auth.uri=bolt://localhost:7687
langchain4j.community.neo4j.auth.user=neo4j
langchain4j.community.neo4j.auth.password=neo4j123
langchain4j.community.neo4j.dimension=2560
langchain4j.community.neo4j.index-name=flight-booking
langchain4j.community.neo4j.database-name=neo4j
langchain4j.community.neo4j.embedding-property=embedding

spring.main.allow-bean-definition-overriding=true

spring.neo4j.uri= bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=neo4j123
#spring.ai.vectorstore.neo4j.initialize-schema=true
#spring.ai.vectorstore.neo4j.index-name=flight-booking
#spring.ai.vectorstore.neo4j.database-name=neo4j
#spring.ai.vectorstore.neo4j.distance-type=cosine
#spring.ai.vectorstore.neo4j.embedding-property=embedding
#spring.ai.vectorstore.neo4j.embedding-dimension=2560